### ISSUE TITLE
AssertionError: %60 : Tensor = onnx::Unsqueeze[axes=[0]](%48)  has empty scope name

### ISSUE THREAD

**Issue by burning846** [lanpa/tensorboardX#404]
An error occurred when I used `add_graph` function, which said 
```
AssertionError: %60 : Tensor = onnx::Unsqueeze[axes=[0]](%48) has empty scope name
````
When I used `verbose=True`, It showed
```
...
  %43 : Float(4, 32, 512, 512) = onnx::Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%0, %1, %2), scope: Generator/DownSample[down0]/Conv2d[conv]
  %44 : Float(4, 32, 512, 512) = onnx::Mul(%43, %43), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %45 : Float(4, 1, 32, 512, 512) = onnx::Unsqueeze[axes=[1]](%44), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %46 : Long() = onnx::Constant[value={0}](), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %47 : Tensor = onnx::Shape(%43), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %48 : Long() = onnx::Gather[axis=0](%47, %46), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %49 : Long() = onnx::Constant[value={1}](), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %50 : Tensor = onnx::Shape(%43), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %51 : Long() = onnx::Gather[axis=0](%50, %49), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %52 : Long() = onnx::Constant[value={2}](), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %53 : Tensor = onnx::Shape(%43), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %54 : Long() = onnx::Gather[axis=0](%53, %52), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %55 : Long() = onnx::Constant[value={3}](), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %56 : Tensor = onnx::Shape(%43), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %57 : Long() = onnx::Gather[axis=0](%56, %55), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %58 : Long() = onnx::Constant[value={1}](), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %59 : Long() = onnx::Constant[value={-1}](), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %60 : Tensor = onnx::Unsqueeze[axes=[0]](%48)
  %61 : Tensor = onnx::Unsqueeze[axes=[0]](%58)
  %62 : Tensor = onnx::Unsqueeze[axes=[0]](%51)
  %63 : Tensor = onnx::Unsqueeze[axes=[0]](%54)
  %64 : Tensor = onnx::Unsqueeze[axes=[0]](%59)
  %65 : Tensor = onnx::Concat[axis=0](%60, %61, %62, %63, %64)
  %66 : Float(4, 1, 32, 512, 512) = onnx::Reshape(%45, %65), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %67 : Float(4, 1, 95, 512, 512) = onnx::Pad[mode="constant", pads=[0, 0, 32, 0, 0, 0, 0, 31, 0, 0], value=0](%66), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %68 : Tensor = onnx::Pad[mode="constant", pads=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], value=0](%67), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %69 : Float(4, 1, 32, 512, 512) = onnx::AveragePool[kernel_shape=[64, 1, 1], pads=[0, 0, 0, 0, 0, 0], strides=[1, 1, 1]](%68), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %70 : Float(4, 32, 512, 512) = onnx::Squeeze[axes=[1]](%69), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %71 : Tensor = onnx::Unsqueeze[axes=[0]](%48)
  %72 : Tensor = onnx::Unsqueeze[axes=[0]](%51)
  %73 : Tensor = onnx::Unsqueeze[axes=[0]](%54)
  %74 : Tensor = onnx::Unsqueeze[axes=[0]](%57)
  %75 : Tensor = onnx::Concat[axis=0](%71, %72, %73, %74)
  %76 : Float(4, 32, 512, 512) = onnx::Reshape(%70, %75), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %77 : Tensor = onnx::Constant[value={1e-08}]()
  %78 : Tensor = onnx::Add(%76, %77)
  %79 : Tensor = onnx::Constant[value={0.5}](), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %80 : Float(4, 32, 512, 512) = onnx::Pow(%78, %79), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %81 : Float(4, 32, 512, 512) = onnx::Div(%43, %80), scope: Generator/DownSample[down0]/LocalResponseNorm[lrn]
  %82 : Float(4, 32, 512, 512) = onnx::LeakyRelu[alpha=0.2](%81), scope: Generator/DownSample[down0]/LeakyReLU[lrelu]
...
```

I found that was probably caused by `nn.LocalResponseNorm` and I wonder how to solve it.

**Comment by jinzhenhh** [comment]
hi, do you know how to solve it now? i got the same runtime error, 
`dummy_input = torch.Tensor(1, 3, 224, 224)
with SummaryWriter(comment='alexnet') as w:
    model = torchvision.models.alexnet()
    w.add_graph(model, (dummy_input, ))`
my pytorch version is 1.0

**Comment by alexdonchuk** [comment]
The same!

**Comment by lanpa** [comment]
Hi all, I have just released tensorboardX 1.8 and tested with torch 1.1.

The following should work without a problem.
```
import torch
import torchvision
from tensorboardX import SummaryWriter

dummy_input = torch.Tensor(1, 3, 224, 224)

with SummaryWriter(comment='alexnet') as w:
    model = torchvision.models.alexnet()
    w.add_graph(model, (dummy_input, ))
```

Reopen the issue if needed, thanks.

**Comment by msieb1** [comment]
Using the newest version 1.8, I still get the following error using the above example with alexnet:

`AssertionError: %34 : Tensor = onnx::Unsqueeze[axes=[0]](%32)
 has empty scope name`
